### PR TITLE
Changed icons to words

### PR DESCRIPTION
**Pull request by Goury**
Because some of my autistic players can't read icons, but can read words just fine.

### CODE REVIEW

**Comment by Kruptein** [comment]
Ok so when I read your mail about text instead of icons I thought the in-game icons where not clear (e.g. vision related icons), I wasn't expecting these icons to be the point of contention.

I personally really like the simplified/minimal button approach, so I'm not keen to change it as the default.

That said I see the validity of your users' concern and I'm willing to make it a customisable user setting using localstorage that defaults to the icons but gives the option in the settings to change to text.

So what I would like to do for this is first pick up the user settings again, which is an ongoing branch on my end that I need to finish and if that's merged further look at this PR.

You can always stash this change so that you can reapply it for your own server in the meanwhile when changes to my code happen.

Does this work for you ?

**Comment by Kruptein** [comment]
Also I would center the create button in the session overview.

**Comment by Goury** [comment]
I don't mind having this change just in my fork, but defaults should totally be administrator-configurable.    
I believe players who already failed an ability check to understand meaning of icons won't succeed on finding a way to adjust settings.

Some of my players seem had rolled –20 for wisdom, so I'd prefer to keep all perception checks DC as low as possible and to have as little of those as possible.  
As for my DMs, they are good.

**Comment by Kruptein** [comment]
The UI of these places has long since changed.

**Pull request closed without merging**
