### PR TITLE
Feature/gh 200 floors

### PR DESCRIPTION
**Pull request by Kruptein**
This PR adds a system to create floors to PA.

These floors are rendered on top of each other with light and vision logic across floors.

You can easily change floors by either using the UI or using the Page Up/Down buttons

### CODE REVIEW

**Comment by AJAnderson** [comment]
So psyched about this!

**Comment by AJAnderson** [comment]
Any tips how to use this? I pulled most recent dev and can't figure it out (sorry I'm a dummy).

**Comment by Kruptein** [comment]
You should see a number in the bottom left indicating the current floor, if you click on it you can add floors and/or change floors.  An example can be seen [here](https://www.planarally.io/blog/2020/02/13/introducing-floors-and-small-updates/)

**Comment by AJAnderson** [comment]
Amazing! Thank you!

**Comment by AJAnderson** [comment]
Incidentally, the reason I didn't see it is that the DM asset tab thingy renders over it. Also noticed some bugs with flicking that view open and closed, the buttons in the bottom left ended up duplicated. Also switching floors with grid on seems to make the grid lines thicker and thicker, only way to clear was to refresh page.

Had a tinker with the floors and it's everything I dreamed of!

**Comment by Kruptein** [comment]
Feel free to open some issues as those obviously need to be resolved.

Thanks for the wonderful feedback :)

**Comment by AJAnderson** [comment]
Definitely will if I can figure out how to re-create it!

**Pull request merged**
