### PR TITLE
Improve visual style of toolbar and layer manager

### PR DESCRIPTION
**Pull request by AntiSC2**
Improves the style of the toolbars by rounding the corners, changing the border color to green and capitalizing the first letter of the names.

screenshotlayers
screenshottoolbar

### CODE REVIEW

**Comment by Kruptein** [comment]
The visual style touches are nice.  The capitalisation is also a nice idea, however editing the js file directly is not advised as it is generated based on the ts source and thus your changes will be overwritten when I build a new js file.

If you want you can change this yourself and I'll wait with merging, otherwise I'll merge the files as such and fix the ts aspect myself.

**Comment by AntiSC2** [comment]
@Kruptein, thanks for the quick review. Did not know about the js file being generated but that actually explains a lot. You can go ahead and merge and fix that mistake.

**Comment by AntiSC2** [comment]
Actually @Kruptein, hold off on merging this one. Just noticed a small gap between the border and the selected element.

**Comment by Kruptein** [comment]
While you're at it could you maybe redo the pr on the dev branch instead?  I would like to keep the master branch release commits.

**Comment by AntiSC2** [comment]
Closing this PR, will redo with the fixes and will push it to the dev branch.

**Pull request closed without merging**
